language: java
dist: xenial
sudo: required
install:
  - TERM=dumb ./gradlew -q assemble
jobs:
  include:
    - name: postgresql 9.6
      jdk: oraclejdk11
      env: PROFILE="-Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql9.6"
      addons:
        postgresql: "9.6"
    - name: postgresql 10
      jdk: oraclejdk11
      env: PROFILE="-Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql10"
      addons:
        postgresql: "10"
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t alf.io .
        - docker images
        - docker tag alf.io $DOCKER_USERNAME/alf.io
        - docker push $DOCKER_USERNAME/alf.io

before_script:
  - psql -c 'create database alfio;' -U postgres
script:
  - TERM=dumb ./gradlew build jacocoTestReport $PROFILE
after_success:
  ./gradlew -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" coveralls
